acme_store_homepage:
    pattern:  /
    defaults: { _controller: AcmeStoreBundle:Default:index }

acme_store_products:
    pattern:  /products
    defaults: { _controller: AcmeStoreBundle:Default:showProducts }

acme_store_categories:
    pattern:  /categories
    defaults: { _controller: AcmeStoreBundle:Default:showCategories }

acme_store_product_description:
    pattern:  /description/product/{id}
    defaults: { _controller: AcmeStoreBundle:Default:descriptionProduct }

acme_store_all_products_of_category:
    pattern:  /description/category/{id}
    defaults: { _controller: AcmeStoreBundle:Default:allProductsOfCategory }

acme_store_fixture:
    pattern:  /fixture
    defaults: { _controller: AcmeStoreBundle:Default:fixture }

acme_store_fixture_done:
    pattern:  /loaddemo
    defaults: { _controller: AcmeStoreBundle:Default:fixtureDone }