parameters:
    weather.class: Acme\StoreBundle\Service\WeatherService
    weather.city: Cherkassy
    name: Cherkassy

services:
    weather.service:
         class: "%weather.class%"
         arguments:    ["%weather.city%"]
         arguments:    ["%name%"]
